# Deployment that logs stuff for demo.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-demo
  namespace: default
  labels:
    app: log-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: log-demo
  template:
    metadata:
      labels:
        app: log-demo
    spec:
      containers:
        - name: log-demo
          image: quay.io/quay/busybox
          command:
            - sh
            - -c
            - 'N=$(expr \( $RANDOM % 100 \) + 50); for x in $(seq $N) ; do echo "$(date) INFO - Hello World - $x of $N"; sleep .1; done; exit 1'
