---
# Forward all logs (audit included) to default LokiStack.
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
spec:
  pipelines:
  - inputRefs:
    - application
    - audit
    - infrastructure
    name: all-to-default
    outputRefs:
    - default
