---
# Used alone will forward application and infrastructure logs to the default LokiStack
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  collection:
    type: vector
  logStore:
     type: lokistack
     lokistack:
       name: logging-loki
